# Generated by Django 6.0.5 on 2026-05-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('math', 'Mathematics'), ('other', 'Other')], max_length=50),
        ),
    ]
