# Generated by Django 6.0.5 on 2026-05-14 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=255)),
                ('application_description', models.TextField()),
                ('application_website', models.URLField(blank=True)),
                ('purchase_required', models.BooleanField(default=False)),
                ('need_virtual_desktop', models.BooleanField(default=False)),
                ('alternative_software_has_been_considered', models.TextField()),
                ('license_agreement_detail', models.TextField(blank=True)),
                ('privacy_considered', models.BooleanField(default=False)),
                ('primary_use', models.CharField(max_length=255)),
                ('need_installing_on', models.TextField()),
                ('need_staff_machine', models.BooleanField(default=False)),
                ('anything_else', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('ticket_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
