# Generated by Django 6.0.5 on 2026-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarerequest',
            name='alternative_software_has_been_considered',
            field=models.BooleanField(default=False),
        ),
    ]
