# Generated by Django 6.0.5 on 2026-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_softwarerequest_alternative_software_has_been_considered'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('opens_at', models.DateField()),
                ('closes_at', models.DateField()),
            ],
        ),
    ]
