# Generated by Django 6.0.5 on 2026-05-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_requestcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarerequest',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
